GET http://localhost:2000/bikes

###
GET http://localhost:2000/bikes/63c9d77d332b2bd94700b3bf
###
POST http://localhost:2000/bikes
Content-Type: application/json

{
    "brand" : "Heft",
    "speed" : "20",
    "color" : "Galaic Purple"
}

###
PATCH http://localhost:2000/bikes/63c9d77d332b2bd94700b3bf
Content-Type: application/json

{
    "brand" : "BMX NEW",
    "speed" : "1",
    "color" : "Rusted Red NEW"
}

###
DELETE http://localhost:2000/bikes/63ca3342645582a23b940c7b